nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://globalaxe.fr']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': # Chemin de votre API Platform
            allow_origin:
                - 'http://localhost:3001'
                - 'https://globalaxe.fr'
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
